export const categories = [
  "Animal Welfare",
  "Arts & Heritage",
  "Children & Youth",
  "Community",
  "Disability",
  "Education",
  "Elderly",
  "Environment",
  "Families",
  "Health",
  "Humanitarian",
  "Social Service",
  "Sports",
  "Women & Girls",
];

export const locations = [
  "Aljunied",
  "Hougang",
  "Ang Mo Kio",
  "Kebun Baru",
  "Yio Chu Kang",
  "Bishan–Toa Payoh",
  "Marymount",
  "Chua Chu Kang",
  "Hong Kah North",
  "East Coast",
  "Holland–Bukit Timah",
  "Bukit Panjang",
  "Jalan Besar",
  "Potong Pasir",
  "Jurong",
  "Bukit Batok",
  "Yuhua",
  "Marine Parade",
  "MacPherson",
  "Mountbatten",
  "Marsiling–Yew Tee",
  "Nee Soon",
  "Pasir Ris–Punggol",
  "Punggol West",
  "Sembawang",
  "SSengkang",
  "Tampines",
  "Tanjong Pagar",
  "Radin Mas",
  "West Coast",
  "Pioneer"
]; 
